### ISSUE TITLE
Move demo geth L1 image to this repo and use current deployment tooling to build it

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#1203]
For historical reasons the image is built in another repo.

The script to build the image is [here](https://github.com/EspressoSystems/espresso-polygon-zkevm-demo/blob/main/scripts/build-l1-image).

The CI action is [here](https://github.com/EspressoSystems/espresso-polygon-zkevm-demo/actions/runs/8175770500/workflow).

The dockerfile is [here](https://github.com/EspressoSystems/espresso-polygon-zkevm-demo/blob/main/docker/geth.Dockerfile).

### TODO
- [ ] Move docker image script to this repo
- [ ] Use current deployment tooling to create image
- [ ] Add CI workflow to build image (in this repo)
- [ ] Update default contract address env vars to match new deployment if necessary. As the contract addresses are a hash of the account nonce and address as long as we deploy from the same account in the same order we get reproducible contract addresses. When deploying with `forge script` files will be saved in the `broadcast` directory, the addresses can be obtained from there. For scripting the `jq` command line tool is useful to work with `JSON`.

**Comment by sveitser** [comment]
This lives in a separate repo now: https://github.com/EspressoSystems/espresso-geth

Since we rarely touch that repo this seems fine to me. Closing.
