### ISSUE TITLE
Open sourcing checklist

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#467]
- [x] README cleanup.
- [x] https://github.com/EspressoSystems/espresso-polygon-zkevm-demo/pull/111
- [x] License in this repo
- [x] License for https://github.com/EspressoSystems/zkevm-contracts
- [x] License for https://github.com/EspressoSystems/hotshot-query-service/
- [x] Make this repo public
- [x] Make https://github.com/EspressoSystems/espresso-polygon-zkevm-demo public
- [x] Make https://github.com/EspressoSystems/hotshot-query-service/ public
- [x] Make https://github.com/EspressoSystems/zkevm-contracts public
- [x] Make https://github.com/EspressoSystems/zkevm-node public
- [x] Replace SSH urls with https urls in Cargo.toml.
- Make packages public:
- [x] https://github.com/orgs/EspressoSystems/packages/container/package/espresso-sequencer%2Fcdn-server
- [x] https://github.com/orgs/EspressoSystems/packages/container/package/espresso-sequencer%2Fsequencer
- [x] https://github.com/orgs/EspressoSystems/packages/container/package/espresso-sequencer%2Fexample-rollup
- [x] https://github.com/orgs/EspressoSystems/packages/container/package/zkevm-node
- [x] https://github.com/orgs/EspressoSystems/packages/container/package/espresso-polygon-zkevm-demo%2Fpolygon-zkevm-adaptor
- [x] https://github.com/orgs/EspressoSystems/packages/container/package/espresso-polygon-zkevm-demo%2Fgeth-with-contracts
- [x] https://github.com/orgs/EspressoSystems/packages/container/package/espresso-polygon-zkevm-demo%2Ffaucet

**Comment by clu8** [comment]
31d36ad185c1e7f3ececad792008cc887a6e86b4
adadee5c2d99ade64cfae0141a3a484a40627961
3d475b74b9330c762ba0157530ce4d50ffdde52e
